// <auto-generated />
namespace EventsApi.Migrations;

using System;
using EventsApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

[DbContext(typeof(DataContext))]
[Migration("20220121232649_InitialMigration")]
partial class InitialMigration
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("Relational:MaxIdentifierLength", 63)
            .HasAnnotation("ProductVersion", "5.0.5")
            .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

        modelBuilder.Entity("EventsApi.Models.Event", b =>
            {
                b.Property<int>("EventId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<string>("Description")
                    .HasColumnType("text");

                b.Property<string>("EventPlace")
                    .HasColumnType("text");

                b.Property<DateTime>("EventTime")
                    .HasColumnType("timestamp without time zone");

                b.Property<string>("Name")
                    .HasColumnType("text");

                b.Property<string>("Organizer")
                    .HasColumnType("text");

                b.Property<string>("Plan")
                    .HasColumnType("text");

                b.Property<string>("Speaker")
                    .HasColumnType("text");

                b.HasKey("EventId");

                b.ToTable("Events");
            });
#pragma warning restore 612, 618
    }
}
